In [2]:
import pandas as pd

In [4]:
df=pd.read_csv('gdp.csv')

In [6]:
df.head()

  Country Name Country Code  Year         Value
0   Arab World          ARB  1968  2.576068e+10
1   Arab World          ARB  1969  2.843420e+10
2   Arab World          ARB  1970  3.138550e+10
3   Arab World          ARB  1971  3.642691e+10
4   Arab World          ARB  1972  4.331606e+10

# Analyzing GDP growth

In [ ]:
#1968-2576
#1969-2843
#1970-3138

In [8]:
2843-2576

267

# Rate of Change in GDP beween 1970 and 1968

In [13]:
round(((3138-2843)/2843)*100,2) # we can use this formula to find gdp growth between 2 years

10.38

# to find rate of change in gdp ,we need to have at least two years to compare. I can not find the rate of change in gdp for 1968 as we do not have the data for 1966

In [21]:
df[df['Country Name']=='Arab World']

   Country Name Country Code  Year         Value
0    Arab World          ARB  1968  2.576068e+10
1    Arab World          ARB  1969  2.843420e+10
2    Arab World          ARB  1970  3.138550e+10
3    Arab World          ARB  1971  3.642691e+10
4    Arab World          ARB  1972  4.331606e+10
5    Arab World          ARB  1973  5.501839e+10
6    Arab World          ARB  1974  1.051458e+11
7    Arab World          ARB  1975  1.163370e+11
8    Arab World          ARB  1976  1.448462e+11
9    Arab World          ARB  1977  1.673083e+11
10   Arab World          ARB  1978  1.835555e+11
11   Arab World          ARB  1979  2.486462e+11
12   Arab World          ARB  1980  3.381775e+11
13   Arab World          ARB  1981  3.485928e+11
14   Arab World          ARB  1982  3.243288e+11
15   Arab World          ARB  1983  3.039625e+11
16   Arab World          ARB  1984  3.079408e+11
17   Arab World          ARB  1985  3.038936e+11
18   Arab World          ARB  1986  2.890292e+11
19   Arab World          ARB  1987  3.126817e+11
20   Arab World          ARB  1988  3.075030e+11
21   Arab World          ARB  1989  3.223251e+11
22   Arab World          ARB  1990  4.468772e+11
23   Arab World          ARB  1991  4.397792e+11
24   Arab World          ARB  1992  4.711635e+11
25   Arab World          ARB  1993  4.765136e+11
26   Arab World          ARB  1994  4.875269e+11
27   Arab World          ARB  1995  5.237599e+11
28   Arab World          ARB  1996  5.782313e+11
29   Arab World          ARB  1997  6.132795e+11
30   Arab World          ARB  1998  5.915256e+11
31   Arab World          ARB  1999  6.438897e+11
32   Arab World          ARB  2000  7.350251e+11
33   Arab World          ARB  2001  7.232828e+11
34   Arab World          ARB  2002  7.290517e+11
35   Arab World          ARB  2003  8.231105e+11
36   Arab World          ARB  2004  9.638623e+11
37   Arab World          ARB  2005  1.184662e+12
38   Arab World          ARB  2006  1.404114e+12
39   Arab World          ARB  2007  1.637573e+12
40   Arab World          ARB  2008  2.078116e+12
41   Arab World          ARB  2009  1.795820e+12
42   Arab World          ARB  2010  2.109646e+12
43   Arab World          ARB  2011  2.501554e+12
44   Arab World          ARB  2012  2.741239e+12
45   Arab World          ARB  2013  2.839627e+12
46   Arab World          ARB  2014  2.906616e+12
47   Arab World          ARB  2015  2.563302e+12
48   Arab World          ARB  2016  2.504703e+12

In [29]:
df_pr = df[df['Country Name']=='Arab World']

In [33]:
df_pr.values

array([['Arab World', 'ARB', 1968, 25760683041.0857],
       ['Arab World', 'ARB', 1969, 28434203615.4829],
       ['Arab World', 'ARB', 1970, 31385499664.0672],
       ['Arab World', 'ARB', 1971, 36426909888.3928],
       ['Arab World', 'ARB', 1972, 43316056615.4562],
       ['Arab World', 'ARB', 1973, 55018394945.5825],
       ['Arab World', 'ARB', 1974, 105145803084.377],
       ['Arab World', 'ARB', 1975, 116337021938.341],
       ['Arab World', 'ARB', 1976, 144846175400.488],
       ['Arab World', 'ARB', 1977, 167308327683.593],
       ['Arab World', 'ARB', 1978, 183555544342.189],
       ['Arab World', 'ARB', 1979, 248646206367.003],
       ['Arab World', 'ARB', 1980, 338177454717.54],
       ['Arab World', 'ARB', 1981, 348592795413.116],
       ['Arab World', 'ARB', 1982, 324328753765.3],
       ['Arab World', 'ARB', 1983, 303962539723.08],
       ['Arab World', 'ARB', 1984, 307940771858.542],
       ['Arab World', 'ARB', 1985, 303893618415.542],
       ['Arab World', 'ARB', 1986, 289029150639.442],
       ['Arab World', 'ARB', 1987, 312681678329.933],
       ['Arab World', 'ARB', 1988, 307503035642.516],
       ['Arab World', 'ARB', 1989, 322325140494.725],
       ['Arab World', 'ARB', 1990, 446877161735.16],
       ['Arab World', 'ARB', 1991, 439779177865.334],
       ['Arab World', 'ARB', 1992, 471163515479.771],
       ['Arab World', 'ARB', 1993, 476513630620.727],
       ['Arab World', 'ARB', 1994, 487526906267.398],
       ['Arab World', 'ARB', 1995, 523759898278.581],
       ['Arab World', 'ARB', 1996, 578231297757.414],
       ['Arab World', 'ARB', 1997, 613279452463.065],
       ['Arab World', 'ARB', 1998, 591525594008.239],
       ['Arab World', 'ARB', 1999, 643889670873.196],
       ['Arab World', 'ARB', 2000, 735025140326.516],
       ['Arab World', 'ARB', 2001, 723282816391.284],
       ['Arab World', 'ARB', 2002, 729051715403.445],
       ['Arab World', 'ARB', 2003, 823110541440.464],
       ['Arab World', 'ARB', 2004, 963862340520.581],
       ['Arab World', 'ARB', 2005, 1184661549595.13],
       ['Arab World', 'ARB', 2006, 1404113530800.68],
       ['Arab World', 'ARB', 2007, 1637573196970.62],
       ['Arab World', 'ARB', 2008, 2078115659876.48],
       ['Arab World', 'ARB', 2009, 1795819607113.11],
       ['Arab World', 'ARB', 2010, 2109645821948.41],
       ['Arab World', 'ARB', 2011, 2501553648412.73],
       ['Arab World', 'ARB', 2012, 2741238538444.31],
       ['Arab World', 'ARB', 2013, 2839626635836.57],
       ['Arab World', 'ARB', 2014, 2906616435186.9],
       ['Arab World', 'ARB', 2015, 2563301730344.96],
       ['Arab World', 'ARB', 2016, 2504702625568.63]], dtype=object)

In [35]:
data =df_pr.values
for i in range(len(data)):
    print(data[i])

['Arab World' 'ARB' 1968 25760683041.0857]
['Arab World' 'ARB' 1969 28434203615.4829]
['Arab World' 'ARB' 1970 31385499664.0672]
['Arab World' 'ARB' 1971 36426909888.3928]
['Arab World' 'ARB' 1972 43316056615.4562]
['Arab World' 'ARB' 1973 55018394945.5825]
['Arab World' 'ARB' 1974 105145803084.377]
['Arab World' 'ARB' 1975 116337021938.341]
['Arab World' 'ARB' 1976 144846175400.488]
['Arab World' 'ARB' 1977 167308327683.593]
['Arab World' 'ARB' 1978 183555544342.189]
['Arab World' 'ARB' 1979 248646206367.003]
['Arab World' 'ARB' 1980 338177454717.54]
['Arab World' 'ARB' 1981 348592795413.116]
['Arab World' 'ARB' 1982 324328753765.3]
['Arab World' 'ARB' 1983 303962539723.08]
['Arab World' 'ARB' 1984 307940771858.542]
['Arab World' 'ARB' 1985 303893618415.542]
['Arab World' 'ARB' 1986 289029150639.442]
['Arab World' 'ARB' 1987 312681678329.933]
['Arab World' 'ARB' 1988 307503035642.516]
['Arab World' 'ARB' 1989 322325140494.725]
['Arab World' 'ARB' 1990 446877161735.16]
['Arab World' 'ARB' 1991 439779177865.334]
['Arab World' 'ARB' 1992 471163515479.771]
['Arab World' 'ARB' 1993 476513630620.727]
['Arab World' 'ARB' 1994 487526906267.398]
['Arab World' 'ARB' 1995 523759898278.581]
['Arab World' 'ARB' 1996 578231297757.414]
['Arab World' 'ARB' 1997 613279452463.065]
['Arab World' 'ARB' 1998 591525594008.239]
['Arab World' 'ARB' 1999 643889670873.196]
['Arab World' 'ARB' 2000 735025140326.516]
['Arab World' 'ARB' 2001 723282816391.284]
['Arab World' 'ARB' 2002 729051715403.445]
['Arab World' 'ARB' 2003 823110541440.464]
['Arab World' 'ARB' 2004 963862340520.581]
['Arab World' 'ARB' 2005 1184661549595.13]
['Arab World' 'ARB' 2006 1404113530800.68]
['Arab World' 'ARB' 2007 1637573196970.62]
['Arab World' 'ARB' 2008 2078115659876.48]
['Arab World' 'ARB' 2009 1795819607113.11]
['Arab World' 'ARB' 2010 2109645821948.41]
['Arab World' 'ARB' 2011 2501553648412.73]
['Arab World' 'ARB' 2012 2741238538444.31]
['Arab World' 'ARB' 2013 2839626635836.57]
['Arab World' 'ARB' 2014 2906616435186.9]
['Arab World' 'ARB' 2015 2563301730344.96]
['Arab World' 'ARB' 2016 2504702625568.63]

In [37]:
data =df_pr.values
for i in range(1,len(data)):
    print(data[i-1],data[i])

['Arab World' 'ARB' 1968 25760683041.0857] ['Arab World' 'ARB' 1969 28434203615.4829]
['Arab World' 'ARB' 1969 28434203615.4829] ['Arab World' 'ARB' 1970 31385499664.0672]
['Arab World' 'ARB' 1970 31385499664.0672] ['Arab World' 'ARB' 1971 36426909888.3928]
['Arab World' 'ARB' 1971 36426909888.3928] ['Arab World' 'ARB' 1972 43316056615.4562]
['Arab World' 'ARB' 1972 43316056615.4562] ['Arab World' 'ARB' 1973 55018394945.5825]
['Arab World' 'ARB' 1973 55018394945.5825] ['Arab World' 'ARB' 1974 105145803084.377]
['Arab World' 'ARB' 1974 105145803084.377] ['Arab World' 'ARB' 1975 116337021938.341]
['Arab World' 'ARB' 1975 116337021938.341] ['Arab World' 'ARB' 1976 144846175400.488]
['Arab World' 'ARB' 1976 144846175400.488] ['Arab World' 'ARB' 1977 167308327683.593]
['Arab World' 'ARB' 1977 167308327683.593] ['Arab World' 'ARB' 1978 183555544342.189]
['Arab World' 'ARB' 1978 183555544342.189] ['Arab World' 'ARB' 1979 248646206367.003]
['Arab World' 'ARB' 1979 248646206367.003] ['Arab World' 'ARB' 1980 338177454717.54]
['Arab World' 'ARB' 1980 338177454717.54] ['Arab World' 'ARB' 1981 348592795413.116]
['Arab World' 'ARB' 1981 348592795413.116] ['Arab World' 'ARB' 1982 324328753765.3]
['Arab World' 'ARB' 1982 324328753765.3] ['Arab World' 'ARB' 1983 303962539723.08]
['Arab World' 'ARB' 1983 303962539723.08] ['Arab World' 'ARB' 1984 307940771858.542]
['Arab World' 'ARB' 1984 307940771858.542] ['Arab World' 'ARB' 1985 303893618415.542]
['Arab World' 'ARB' 1985 303893618415.542] ['Arab World' 'ARB' 1986 289029150639.442]
['Arab World' 'ARB' 1986 289029150639.442] ['Arab World' 'ARB' 1987 312681678329.933]
['Arab World' 'ARB' 1987 312681678329.933] ['Arab World' 'ARB' 1988 307503035642.516]
['Arab World' 'ARB' 1988 307503035642.516] ['Arab World' 'ARB' 1989 322325140494.725]
['Arab World' 'ARB' 1989 322325140494.725] ['Arab World' 'ARB' 1990 446877161735.16]
['Arab World' 'ARB' 1990 446877161735.16] ['Arab World' 'ARB' 1991 439779177865.334]
['Arab World' 'ARB' 1991 439779177865.334] ['Arab World' 'ARB' 1992 471163515479.771]
['Arab World' 'ARB' 1992 471163515479.771] ['Arab World' 'ARB' 1993 476513630620.727]
['Arab World' 'ARB' 1993 476513630620.727] ['Arab World' 'ARB' 1994 487526906267.398]
['Arab World' 'ARB' 1994 487526906267.398] ['Arab World' 'ARB' 1995 523759898278.581]
['Arab World' 'ARB' 1995 523759898278.581] ['Arab World' 'ARB' 1996 578231297757.414]
['Arab World' 'ARB' 1996 578231297757.414] ['Arab World' 'ARB' 1997 613279452463.065]
['Arab World' 'ARB' 1997 613279452463.065] ['Arab World' 'ARB' 1998 591525594008.239]
['Arab World' 'ARB' 1998 591525594008.239] ['Arab World' 'ARB' 1999 643889670873.196]
['Arab World' 'ARB' 1999 643889670873.196] ['Arab World' 'ARB' 2000 735025140326.516]
['Arab World' 'ARB' 2000 735025140326.516] ['Arab World' 'ARB' 2001 723282816391.284]
['Arab World' 'ARB' 2001 723282816391.284] ['Arab World' 'ARB' 2002 729051715403.445]
['Arab World' 'ARB' 2002 729051715403.445] ['Arab World' 'ARB' 2003 823110541440.464]
['Arab World' 'ARB' 2003 823110541440.464] ['Arab World' 'ARB' 2004 963862340520.581]
['Arab World' 'ARB' 2004 963862340520.581] ['Arab World' 'ARB' 2005 1184661549595.13]
['Arab World' 'ARB' 2005 1184661549595.13] ['Arab World' 'ARB' 2006 1404113530800.68]
['Arab World' 'ARB' 2006 1404113530800.68] ['Arab World' 'ARB' 2007 1637573196970.62]
['Arab World' 'ARB' 2007 1637573196970.62] ['Arab World' 'ARB' 2008 2078115659876.48]
['Arab World' 'ARB' 2008 2078115659876.48] ['Arab World' 'ARB' 2009 1795819607113.11]
['Arab World' 'ARB' 2009 1795819607113.11] ['Arab World' 'ARB' 2010 2109645821948.41]
['Arab World' 'ARB' 2010 2109645821948.41] ['Arab World' 'ARB' 2011 2501553648412.73]
['Arab World' 'ARB' 2011 2501553648412.73] ['Arab World' 'ARB' 2012 2741238538444.31]
['Arab World' 'ARB' 2012 2741238538444.31] ['Arab World' 'ARB' 2013 2839626635836.57]
['Arab World' 'ARB' 2013 2839626635836.57] ['Arab World' 'ARB' 2014 2906616435186.9]
['Arab World' 'ARB' 2014 2906616435186.9] ['Arab World' 'ARB' 2015 2563301730344.96]
['Arab World' 'ARB' 2015 2563301730344.96] ['Arab World' 'ARB' 2016 2504702625568.63]

In [41]:
data =df_pr.values 
for i in range (1,len(data)):

    prev =data[i-1][3]
    cur=data[i][3]
    print( data[i][2] , round(((cur-prev)/prev)*100,2))      #[3]-specifying take column 3 data

1969 10.38
1970 10.38
1971 16.06
1972 18.91
1973 27.02
1974 91.11
1975 10.64
1976 24.51
1977 15.51
1978 9.71
1979 35.46
1980 36.01
1981 3.08
1982 -6.96
1983 -6.28
1984 1.31
1985 -1.31
1986 -4.89
1987 8.18
1988 -1.66
1989 4.82
1990 38.64
1991 -1.59
1992 7.14
1993 1.14
1994 2.31
1995 7.43
1996 10.4
1997 6.06
1998 -3.55
1999 8.85
2000 14.15
2001 -1.6
2002 0.8
2003 12.9
2004 17.1
2005 22.91
2006 18.52
2007 16.63
2008 26.9
2009 -13.58
2010 17.48
2011 18.58
2012 9.58
2013 3.59
2014 2.36
2015 -11.81
2016 -2.29

In [47]:
data = df_pr.values 

gdp_change=[0]

for i in range (1,len(data)):

    prev =data[i-1][3]
    cur = data[i][3]
    gdp_change.append(round(((cur-prev)/prev)*100,2) )     #[3]-specifying take column 3 data

In [49]:
gdp_change

[0,
 10.38,
 10.38,
 16.06,
 18.91,
 27.02,
 91.11,
 10.64,
 24.51,
 15.51,
 9.71,
 35.46,
 36.01,
 3.08,
 -6.96,
 -6.28,
 1.31,
 -1.31,
 -4.89,
 8.18,
 -1.66,
 4.82,
 38.64,
 -1.59,
 7.14,
 1.14,
 2.31,
 7.43,
 10.4,
 6.06,
 -3.55,
 8.85,
 14.15,
 -1.6,
 0.8,
 12.9,
 17.1,
 22.91,
 18.52,
 16.63,
 26.9,
 -13.58,
 17.48,
 18.58,
 9.58,
 3.59,
 2.36,
 -11.81,
 -2.29]

In [51]:
df_pr.assign(GDP = gdp_change) #adding new column to data

   Country Name Country Code  Year         Value    GDP
0    Arab World          ARB  1968  2.576068e+10   0.00
1    Arab World          ARB  1969  2.843420e+10  10.38
2    Arab World          ARB  1970  3.138550e+10  10.38
3    Arab World          ARB  1971  3.642691e+10  16.06
4    Arab World          ARB  1972  4.331606e+10  18.91
5    Arab World          ARB  1973  5.501839e+10  27.02
6    Arab World          ARB  1974  1.051458e+11  91.11
7    Arab World          ARB  1975  1.163370e+11  10.64
8    Arab World          ARB  1976  1.448462e+11  24.51
9    Arab World          ARB  1977  1.673083e+11  15.51
10   Arab World          ARB  1978  1.835555e+11   9.71
11   Arab World          ARB  1979  2.486462e+11  35.46
12   Arab World          ARB  1980  3.381775e+11  36.01
13   Arab World          ARB  1981  3.485928e+11   3.08
14   Arab World          ARB  1982  3.243288e+11  -6.96
15   Arab World          ARB  1983  3.039625e+11  -6.28
16   Arab World          ARB  1984  3.079408e+11   1.31
17   Arab World          ARB  1985  3.038936e+11  -1.31
18   Arab World          ARB  1986  2.890292e+11  -4.89
19   Arab World          ARB  1987  3.126817e+11   8.18
20   Arab World          ARB  1988  3.075030e+11  -1.66
21   Arab World          ARB  1989  3.223251e+11   4.82
22   Arab World          ARB  1990  4.468772e+11  38.64
23   Arab World          ARB  1991  4.397792e+11  -1.59
24   Arab World          ARB  1992  4.711635e+11   7.14
25   Arab World          ARB  1993  4.765136e+11   1.14
26   Arab World          ARB  1994  4.875269e+11   2.31
27   Arab World          ARB  1995  5.237599e+11   7.43
28   Arab World          ARB  1996  5.782313e+11  10.40
29   Arab World          ARB  1997  6.132795e+11   6.06
30   Arab World          ARB  1998  5.915256e+11  -3.55
31   Arab World          ARB  1999  6.438897e+11   8.85
32   Arab World          ARB  2000  7.350251e+11  14.15
33   Arab World          ARB  2001  7.232828e+11  -1.60
34   Arab World          ARB  2002  7.290517e+11   0.80
35   Arab World          ARB  2003  8.231105e+11  12.90
36   Arab World          ARB  2004  9.638623e+11  17.10
37   Arab World          ARB  2005  1.184662e+12  22.91
38   Arab World          ARB  2006  1.404114e+12  18.52
39   Arab World          ARB  2007  1.637573e+12  16.63
40   Arab World          ARB  2008  2.078116e+12  26.90
41   Arab World          ARB  2009  1.795820e+12 -13.58
42   Arab World          ARB  2010  2.109646e+12  17.48
43   Arab World          ARB  2011  2.501554e+12  18.58
44   Arab World          ARB  2012  2.741239e+12   9.58
45   Arab World          ARB  2013  2.839627e+12   3.59
46   Arab World          ARB  2014  2.906616e+12   2.36
47   Arab World          ARB  2015  2.563302e+12 -11.81
48   Arab World          ARB  2016  2.504703e+12  -2.29